baseURL = "https://oblac.rs/"
languageCode = "en-us"
title = "Oblac"

[Author]
  name="igor"
  homepage = "https://igo.rs/"

[params]
  description = "Oblac: blog / kod / mišljenja / stavovi / lično"
  githubUsername = "igr"
  tagline = "blog / kod / mišljenja / stavovi / lično"

[permalinks]
  posts = "/:slug"

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
