baseURL = "https://oblac.rs/"
languageCode = "en-us"
title = "Oblac"

[Author]
  name="igor"
  homepage = "https://igo.rs/"

[params]
  description = "Oblac. Blog. Kod. Razmišljanja. Stavovi."
  githubUsername = "igr"
  tagline = "Blog. Kod. Razmišljanja. Stavovi."

[permalinks]
  posts = "/:slug"

[blackfriday]
  hrefTargetBlank = true